# Generated by Django 3.2.18 on 2023-08-11 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('request_type', models.CharField(choices=[('New Connection', 'New Connection'), ('Cylinder_Booking', 'Cylinder_Booking'), ('Change_Address', 'Change_Address'), ('Cylinder_Delivery', 'Cylinder_Delivery')], max_length=100)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
