# Generated by Django 3.2.18 on 2023-08-11 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gas_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasservicerequest',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasservicerequest',
            name='request_type',
            field=models.CharField(choices=[('New Connection', 'New Connection'), ('Cylinder_Booking', 'Cylinder Booking'), ('Change_Address', 'Change Address'), ('Cylinder_Delivery', 'Cylinder Delivery')], max_length=100),
        ),
    ]
